services:
  app:
    build: .
    ports:
      - "6654:6654"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./images:/app/images

  ngrok:
    image: ngrok/ngrok:latest
    command: http --url=auesassets.ngrok.dev app:6654
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - app
